version: '3'

services:
  app:
    image: ${CI_REGISTRY_IMAGE}/app:latest
    build:
      context: .
      dockerfile: app/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks:
      - web

networks:
  web:
    external:
      name: web