version: '3'

services:
  nginx:
    image: qwer342/todo_nginx:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - app
    networks:
      - web

  app:
    image: qwer342/todo_app:latest
    build:
      context: .
      dockerfile: app/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks:
      - web

networks:
  web:
    external:
      name: web