name: "Main workflow"

on:
  push:
    branches:
      - 'main'
jobs:
  set-up:
    runs-on: self-hosted
    steps:
      - name: SetUp QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Pull
        uses: actions/checkout@v2

  build:
    needs: set-up
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker image build . --file app/Dockerfile --tag qwer342/todo_app:latest

      - name: Push Docker Image
        run: docker image push qwer342/todo_app:latest

      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker image build . --file deploy/nginx/Dockerfile --tag qwer342/todo_nginx:latest

      - name: Push Docker Image
        run: docker image push qwer342/todo_nginx:latest