name: "Main workflow"

on:
  push:
    branches:
      - 'main'
jobs:
  set-up:
    runs-on: self-hosted
    steps:
      - name: SetUp QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Pull
        uses: actions/checkout@v2

  build:
    needs: set-up
    runs-on: self-hosted
    steps:
      - name: Executing remote ssh commands to set env
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USER }}
            key: ${{ secrets.SSH_KEY }}
            script: |
                export NEWS_TOKEN=${{ secrets.NEWS_TOKEN }}
                export API_URL=${{ secrets.API_URL }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker image build . --file app/Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/todo_app:latest

      - name: Push Docker Image
        run: docker image push ${{ secrets.DOCKER_HUB_USERNAME }}/todo_app:latest

      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker image build . --file deploy/nginx/Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/todo_nginx:latest

      - name: Push Docker Image
        run: docker image push ${{ secrets.DOCKER_HUB_USERNAME }}/todo_nginx:latest

  deployment:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Executing remote ssh commands to set env
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USER }}
            key: ${{ secrets.SSH_KEY }}
            script: |
              export NEWS_TOKEN=${{ secrets.NEWS_TOKEN }}
              export API_URL=${{ secrets.API_URL }}

      - name: Make pull
        uses: actions/checkout@v2

      - name: Stop containers
        run: docker-compose stop

      - name: Remove containers
        run: docker-compose rm -f

      - name: Start container
        run: CURRENT_UID=$(id -u):$(id -g) docker-compose up --build -d